---
title: "Meta-Analyses of the Temporal Stability and Convergent Validity of Risk Preference Measures"
output: 
  html_document:
    toc: false
    toc_float: false
---


<!-- <style type="text/css"> -->
<!--   body{ -->
<!--   font-size: 12pt; -->
<!--   font-family: "Source Sans 3"; -->
<!-- } -->
<!-- </style> -->



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
```


### Alexandra Bagaïni<sup>1</sup>, Yunrui Liu<sup>1</sup>, Madlaina Kapoor<sup>1</sup>, Gayoung Son<sup>2</sup>, Paul-Christian Bürkner<sup>3</sup>, Loreen Tisdall<sup>1</sup>, and Rui Mata<sup>1</sup>

<sup>1</sup>Center for Cognitive and Decision Sciences, University of Basel; <sup>2</sup>Department of Psychology, University of Bern; <sup>3</sup>Department of Statistics, TU Dortmund University


<br>

## About the study

Understanding whether risk preference represents a stable, coherent trait is central to efforts aimed at explaining, predicting, and preventing risk-related behaviours. We help characterise the nature of the construct by adopting an individual participant data meta-analytic approach to summarise the temporal stability of over 350 risk preference measures (33 panels, 57 samples, >575,000 respondents). Our findings reveal significant heterogeneity across and within measure categories (propensity, frequency, behaviour),domains (e.g., investment, occupational, alcohol consumption), and sample characteristics(e.g., age). Specifically, while self-reported propensity and frequency measures of risk preference show a higher degree of stability relative to behavioural measures, these patterns are moderated by domain and age. Crucially, an analysis of convergent validity reveals a low agreement across measures, questioning the idea that they capture the same underlying phenomena. Our results raise concerns about the coherence and measurement of the risk preference construct.

<br>

A pre-print is accessible on [PsyArxiv](https://psyarxiv.com/d7nuj/). 
We make the estimated test-retest correlations and inter-correlations from the primary data sources as well as all analysis scripts publicly available in an [OSF repository](https://osf.io/5kzgd/). 

<br>

## About the companion website

This is the companion website for the study ***Comparing the Temporal Stability and Convergent Validity of Risk Preference Measures: A Meta-Analytic Approach***. Here, we provide additional information on the data, analyses and results reported in the [manuscript](https://psyarxiv.com/d7nuj/):

 - **[Data](https://cdsbasel.github.io/temprisk/data_desc.html):** Information on the sources of the data included in the analyses.
 - **[Workflow](https://cdsbasel.github.io/temprisk/workflow_overview.html):** Step-by-step instructions on how to use the files in the OSF repository to replicate the analyses described in the paper.
 - **[Processing](https://cdsbasel.github.io/temprisk/processing_overview.html):**  Supplementary overview of the test-retest correlations and inter-correlations.
 <!--    - ***Test-Retest Correlations*** -->
 <!--    - ***Inter-Correlations*** -->
 <!-- Overview of the data pre-processing steps as well as the computation of test-retest correlations and inter-correlations using the scripts available on the OSF repository. -->
 - **Analysis:** Supplementary information on the analyses and results.
   - ***[Variance Decomposition](https://cdsbasel.github.io/temprisk/var_decomp_overview.html):*** Descriptions of the effects examined for the variance decomposition analysis of test-retest correlations and inter-correlations, separately.
   - ***[Temporal Stability](https://cdsbasel.github.io/temprisk/masc_overview.html):*** Model summaries, MCMC diagnostics and posterior predictive checks.
   - ***[Convergent Validity](https://cdsbasel.github.io/temprisk/ma_bivar_overview.html):*** Model summaries, MCMC diagnostics and posterior predictive checks, as well as robustness checks.
 - **[Multiverse](https://cdsbasel.github.io/temprisk/multiverse_overview.html):** Summary output showing the robustness of the results of the above-mentioned analyses to variations in the processed data.


<br>
<br>






